Models/Event.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TelephoneCallsWebApplication.Models
{
    [Table("T_EVENT")]
    public class Event
    {
        [Column("RECORD_ID")]
        public int ID { get; set; }

        [Column("CALL_ID")]
        public int CallID { get; set; }

        [Required]
        [Column("RECORD_EVENT_ID")]
        public string EventTypeID { get; set; }

        [Column("RECORD_DATE")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm:ss}", ApplyFormatInEditMode = true)]
        public DateTime Date { get; set; }

        public EventType EventType { get; set; } 
        
        public Call Call { get; set; }

        public Event()
        {

        }

        public Event(EventType type, DateTime timestamp, Call call)
        {
            EventType = type;
            Date = timestamp;
            Call = call;

            CallID = call.ID;
            EventTypeID = type.ID;
        }
    }
}

Models/EventType.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TelephoneCallsWebApplication.Models
{
    [Table("T_EVENT_TYPE")]
    public class EventType
    {
        public static readonly EventType EventPickUp = new EventType("EVENT_PICK_UP", "Pick-up");
        public static readonly EventType EventDial = new EventType("EVENT_DIAL", "Dialling");
        public static readonly EventType EventCallEstablished = new EventType("EVENT_CALL_ESTABLISHED", "Call Established");
        public static readonly EventType EventCallEnd = new EventType("EVENT_CALL_END", "Call End");
        public static readonly EventType EventHangUp = new EventType("EVENT_HANG_UP", "Hang-up");

        [Column("EVENT_ID")]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public string ID { get; set; }

        [Required]
        [Column("EVENT_NAME")]
        public string EventName { get; private set; }

        public EventType()
        {

        }

        public EventType(string id, string name)
        {
            ID = id;
            EventName = name;
        }

        public static string GetEventTypeById(string id)
        {
            switch (id)
            {
                case "EVENT_PICK_UP":
                    return EventPickUp.EventName;
                case "EVENT_DIAL":
                    return EventDial.EventName;
                case "EVENT_CALL_ESTABLISHED":
                    return EventCallEstablished.EventName;
                case "EVENT_CALL_END":
                    return EventCallEnd.EventName;
                case "EVENT_HANG_UP":
                    return EventHangUp.EventName;
                default:
                    return string.Empty;
            }
        }
    }
}

Controllers/CallsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;
using TelephoneCallsWebApplication.Data;
using TelephoneCallsWebApplication.Models;

namespace TelephoneCallsWebApplication.Controllers
{
    public class CallsController : Controller
    {
        private readonly TelephoneCallsContext _context;
        private readonly IStringLocalizer<HomeController> _localizer;

        public CallsController(TelephoneCallsContext context, IStringLocalizer<HomeController> localizer)
        {
            _context = context;
            _localizer = localizer;
        }

        // GET: Calls/Details/3333333
        public async Task<IActionResult> Details(int? phoneNumber)
        {
            if (phoneNumber == null)
            {
                return NotFound();
            }

            var calls = await _context.Calls
                .Include(x => x.Events).Where(x => x.Caller == phoneNumber).ToListAsync();

            if (calls == null)
            {
                return NotFound();
            }

            ViewData["phoneNumber"] = phoneNumber.Value;

            var vcalls = calls.ToList().OrderByDescending(x => x.Timestamp).ToList();

            return View(vcalls);
        }
    }
}

Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;
using TelephoneCallsWebApplication.Data;
using TelephoneCallsWebApplication.Models;

namespace TelephoneCallsWebApplication.Controllers
{
    public class EventsController : Controller
    {
        private const int DEFAULT_PAGE_SIZE = 5;

        private readonly IStringLocalizer<HomeController> _localizer;
        private readonly TelephoneCallsContext _context;
        private IHostingEnvironment _hostingEnvironment;

        public EventsController(TelephoneCallsContext context, IHostingEnvironment hostingEnvironment, IStringLocalizer<HomeController> localizer)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
            _localizer = localizer;
        }

        // GET: Events
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, string searchBy, int? page, int? pageSize, List<string> eventTypes)
        {
            ViewData["CallerSortParm"] = String.IsNullOrEmpty(sortOrder) ? "caller_desc" : "";
            ViewData["ReceiverSortParm"] = sortOrder == "Receiver" ? "receiver_desc" : "Receiver";
            searchBy = !string.IsNullOrWhiteSpace(searchBy) ? searchBy : ((ViewData["SearchBy"] == null) ? "Caller" : ViewData["SearchBy"].ToString());
            ViewData["SearchBy"] = searchBy;
            ViewData["CurrentSort"] = sortOrder;

            foreach (var item in eventTypes)
            {
                ViewData["EventTypes"] += (item + ',');
            }
         
            if (!string.IsNullOrEmpty(searchString))
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var events = GetFilteredAndSortedData(eventTypes, searchString, searchBy, sortOrder);

            int recordsPerPage = pageSize.HasValue ? pageSize.Value : DEFAULT_PAGE_SIZE;
            ViewData["PageSize"] = recordsPerPage;
            return View(await PaginatedList<Event>.CreateAsync(events.AsNoTracking(), page ?? 1, recordsPerPage));
        }

        private IQueryable<Event> GetFilteredAndSortedData(List<string> eventTypes, string searchString, string searchBy, string sortOrder)
        {
            if (eventTypes.Count == 0)
            {
                eventTypes = new List<string>()
                {
                    EventType.EventDial.EventName,
                    EventType.EventHangUp.EventName,
                    EventType.EventPickUp.EventName,
                    EventType.EventCallEstablished.EventName,
                    EventType.EventCallEnd.EventName
                };
            }

            if (eventTypes.Count == 1)
            {
                eventTypes = eventTypes[0].Split(',').ToList();
            }

            var events = from _event in _context.Events.Include(x => x.Call).Include(x => x.EventType) select _event;
            events = events.Where(x => eventTypes.Contains(x.EventType.EventName));

            if (!string.IsNullOrEmpty(searchString))
            {
                if (!string.IsNullOrWhiteSpace(searchBy) && searchBy == "Receiver")
                {
                    events = events.Where(x => x.Call.Receiver.ToString().StartsWith(searchString));
                }
                else
                {
                    events = events.Where(x => x.Call.Caller.ToString().StartsWith(searchString));
                }
            }
            switch (sortOrder)
            {
                case "caller_desc":
                    events = events.OrderByDescending(x => x.Call.Caller);
                    break;
                case "Receiver":
                    events = events.OrderBy(x => x.Call.Receiver);
                    break;
                case "receiver_desc":
                    events = events.OrderByDescending(x => x.Call.Receiver);
                    break;
                default:
                    events = events.OrderBy(x => x.Call.Caller);
                    break;
            }
            return events;

        }

        // GET: Events/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var _event = await _context.Events
                .Include(x => x.Call).Include(x => x.Call.Events)
                .Include(x => x.EventType)
                .SingleOrDefaultAsync(m => m.ID == id);

            if (_event == null)
            {
                return NotFound();
            }

            _event.Call.Events = _event.Call.Events.OrderBy(x => x.Date).ToList();

            return View(_event);
        }

        // POST: Events/Export
        public async Task<IActionResult> Export(string sortOrder, string currentFilter, string searchBy, List<string> eventTypes)
        {
            string sWebRootFolder = _hostingEnvironment.WebRootPath;
            DateTime todayDate = DateTime.Now;
            string month = todayDate.Month.ToString();
            month = month.Length == 1 ? "0" + month : month;
            string day = todayDate.Day.ToString();
            day = day.Length == 1 ? "0" + day : day;
            string todayString = todayDate.Year.ToString() + month + day;
            string fileName = "all_records_" + todayString + ".csv";
            string sFileName = @fileName;
            string URL = string.Format("{0}://{1}/{2}", Request.Scheme, Request.Host, sFileName);
            FileInfo file = new FileInfo(Path.Combine(sWebRootFolder, sFileName));
            var memory = new MemoryStream();
            using (var fs = new FileStream(Path.Combine(sWebRootFolder, sFileName), FileMode.Create, FileAccess.Write))
            {
                IWorkbook workbook;
                workbook = new XSSFWorkbook();
                ISheet excelSheet = workbook.CreateSheet(_localizer["All Records"]);
                IRow row = excelSheet.CreateRow(0);
                row.CreateCell(0).SetCellValue(_localizer["Caller"]);
                row.CreateCell(1).SetCellValue(_localizer["Event"]);
                row.CreateCell(2).SetCellValue(_localizer["Receiver"]);
                row.CreateCell(3).SetCellValue(_localizer["Timestamp"]);

                var events = GetFilteredAndSortedData(eventTypes, currentFilter, searchBy, sortOrder).ToList();
                for (int i = 1; i <= events.Count(); i++)
                {
                    row = excelSheet.CreateRow(i);
                    row.CreateCell(0).SetCellValue(events[i - 1].Call.Caller.ToString());
                    row.CreateCell(1).SetCellValue(events[i - 1].EventType.EventName);
                    row.CreateCell(2).SetCellValue(events[i - 1].Call.Receiver.HasValue ? events[i - 1].Call.Receiver.Value.ToString() : "-");
                    row.CreateCell(3).SetCellValue(events[i - 1].Date.ToString("dd/MM/yyyy HH:mm:ss"));
                }
                workbook.Write(fs);
            }
            using (var stream = new FileStream(Path.Combine(sWebRootFolder, sFileName), FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            memory.Position = 0;
            return File(memory, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", sFileName);
        }
    }
}

Views/Events/Details.cshtml
@model TelephoneCallsWebApplication.Models.Event
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = Localizer["Call Details"];
}

<h2>@Localizer["Call Details"]</h2>

<div>
    <h4>@Localizer["Caller"] # @Model.Call.Caller : @Localizer[Model.Call.CallType]</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Localizer["Receiver"]:
        </dt>
        <dd>
            @Html.DisplayFor(modelItem => Model.Call.Receiver)
        </dd>
        <dt>
            @Localizer["Events"]:
        </dt>
        <dd>
            <table class="table">
                <tr>
                    <th>@Localizer["Event"]</th>
                    <th>@Localizer["Event Date"]</th>
                </tr>
                @foreach (var item in Model.Call.Events)
                {
                    <tr>
                        <td>
                            @Localizer[EventType.GetEventTypeById(item.EventTypeID)]
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Date)
                        </td>
                    </tr>
                }
            </table>
        </dd>
    </dl>
</div>

<div>
    <a asp-action="Index">@Localizer["Back to List"]</a>
</div>

Views/Events/Index.cshtml
@using TelephoneCallsWebApplication.Data;
@using TelephoneCallsWebApplication.Models;
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model PaginatedList<TelephoneCallsWebApplication.Models.Event>


@{
    ViewData["Title"] = Localizer["Event Records"];
    
    var choiceList = new List<string> { "Caller", "Receiver" };
    string searchBy = "";
    List<string> chooseEventTypes = new List<string>()
    {
        EventType.EventDial.EventName,
        EventType.EventHangUp.EventName,
        EventType.EventPickUp.EventName,
        EventType.EventCallEstablished.EventName,
        EventType.EventCallEnd.EventName
    };
    List<string> eventTypes = new List<string>();
}

<h2>@Localizer["Event Records"]</h2>

<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <div class="form-group">
            <label asp-for="@searchBy" class="control-label">@Localizer["Search by"] </label>
            <select class="dropdown" asp-for="@searchBy">
                @foreach (string choice in choiceList)
                {
                    <option value="@choice">@Localizer[choice]</option>
                }
            </select>
            <input type="text" name="SearchString" value="@ViewData["currentFilter"]" />
        </div>
        <div class="form-group">
            <label asp-for="@eventTypes" class="control-label">@Localizer["Event types (hold ctrl to select more than one)"]:</label>
            <select id="eventTypeSelect" multiple class="form-control" asp-for="@eventTypes">
                @foreach (string type in chooseEventTypes)
                {
                    bool selected = (ViewData["EventTypes"] != null) ? ViewData["EventTypes"].ToString().Contains(type) : false;
                    <option value=@type selected=@selected>@Localizer[type]</option>
                }
            </select>
            <input type="submit" value="@Localizer["Search"]" class="btn btn-default" /> |
            <a asp-action="Index"
               asp-route-pageSize="@ViewData["PageSize"]">@Localizer["Back to Full List"]</a>
        </div>
    </div>
</form>

<form method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="col-md-8" style="padding-top:10px;">
            <button asp-action="Export"
                    asp-route-sortOrder="@ViewData["CurrentSort"]"
                    asp-route-currentFilter="@ViewData["CurrentFilter"]"
                    asp-route-searchBy="@ViewData["SearchBy"]"
                    asp-route-eventTypes="@ViewData["EventTypes"]">
                @Localizer["Export"]
            </button>
        </div>
    </div>
</form>

<table class="table table-hover">
    <thead>
        <tr>
            <th>
                <a asp-action="Index"
                   asp-route-sortOrder="@ViewData["CallerSortParm"]"
                   asp-route-currentFilter="@ViewData["CurrentFilter"]"
                   asp-route-pageSize="@ViewData["PageSize"]"
                   asp-route-searchBy="@ViewData["SearchBy"]">@Localizer["Caller"]</a>
</th>
            <th>
                @Localizer["Event"]
            </th>
            <th>
                <a asp-action="Index"
                   asp-route-sortOrder="@ViewData["ReceiverSortParm"]"
                   asp-route-currentFilter="@ViewData["CurrentFilter"]"
                   asp-route-pageSize="@ViewData["PageSize"]"
                   asp-route-searchBy="@ViewData["SearchBy"]">@Localizer["Receiver"]</a>
</th>
            <th>
                @Localizer["Timestamp"]
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr onclick="location.href = '@(Url.Action("Details", "Events", new { id = item.ID }))'">
                <td>
                    <a href="@(Url.Action("Details", "Calls", new { phoneNumber = item.Call.Caller }))">@item.Call.Caller</a>
                </td>
                <td>
                    @Localizer[item.EventType.EventName]
                </td>
                <td>
                    @(item.Call.Receiver.HasValue ? item.Call.Receiver.Value.ToString() : "-")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
            </tr>
        }
    </tbody>
</table>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-page="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   asp-route-pageSize="@ViewData["PageSize"]"
   asp-route-searchBy="@ViewData["SearchBy"]"
   asp-route-eventTypes="@ViewData["EventTypes"]"
   class="btn btn-default @prevDisabled">
    @Localizer["Previous"]
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-page="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   asp-route-pageSize="@ViewData["PageSize"]"
   asp-route-searchBy="@ViewData["SearchBy"]"
   asp-route-eventTypes="@ViewData["EventTypes"]"
   class="btn btn-default @nextDisabled">
    @Localizer["Next"]
</a>

<div style="display:flex; padding-top:20px;">
    <b>@Localizer["Records per page"]:</b>
    <div class="dropdown">
        <button class="btn btn-default dropdown-toggle" data-toggle="dropdown" type="button">@ViewData["PageSize"]<span class="caret"></span></button>
        <ul class="dropdown-menu">
            <li>
                <a asp-action="Index"
                   asp-route-pageSize=5>5</a>
            </li>
            <li>
                <a asp-action="Index"
                   asp-route-pageSize=10>10</a>
            </li>
            <li>
                <a asp-action="Index"
                   asp-route-pageSize=25>25</a>
            </li>
        </ul>
    </div>
</div>